import type { Metadata } from "next";
import { Geist, Aclonica } from "next/font/google";
import "./globals.css";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import { StyledEngineProvider } from "@mui/material";

const geist = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const aclonica = Aclonica({
  variable: "--font-alconica",
  weight: '400'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${geist.variable} ${aclonica.variable}`}>
      <AppRouterCacheProvider>
        <StyledEngineProvider injectFirst>
          <body>{children}</body>
        </StyledEngineProvider>
      </AppRouterCacheProvider>
    </html>
  );
}
